name: Ady RDP Free (LocalXpose)

on:
  workflow_dispatch:

jobs:
  free-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: ⚙️ Configure RDP and Firewall
        run: |
          # Enable RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name "SecurityLayer" -Value 0 -Force

          # Disable Firewall (All Profiles)
          Write-Host "Disabling Windows Firewall..."
          netsh advfirewall set allprofiles state off
          Write-Host "Windows Firewall disabled successfully."

          # Restart RDP service
          Restart-Service -Name TermService -Force

      - name: 👤 Create RDP User
        run: |
          $password = "Akudankamu1@,"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          
          if (-not (Get-LocalUser -Name "Ady" -ErrorAction SilentlyContinue)) {
              New-LocalUser -Name "Ady" -Password $securePass -AccountNeverExpires
              Add-LocalGroupMember -Group "Administrators" -Member "Ady"
              Add-LocalGroupMember -Group "Remote Desktop Users" -Member "Ady"
          } else {
              Set-LocalUser -Name "Ady" -Password $securePass
          }

          echo "RDP_CREDS=User: Ady | Password: $password" >> $env:GITHUB_ENV

      - name: 🧩 Download LocalXpose
  run: |
    Invoke-WebRequest https://api.localxpose.io/api/v2/downloads/lx-windows-amd64.zip -OutFile lx.zip
    Expand-Archive lx.zip -DestinationPath .
      - name: 🔑 Authenticate LocalXpose
        run: |
          & "$env:USERPROFILE\lx.exe" authtoken ${{ secrets.LOCALXPOSE_TOKEN }}

      - name: 🚀 Start Public RDP Tunnel
        run: |
          Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\lx.exe" -ArgumentList "tcp --port 3389"
          Start-Sleep -Seconds 10
          Write-Host "🔍 Fetching tunnel info..."
          & "$env:USERPROFILE\lx.exe" tunnels list

      - name: 🖥️ Display RDP Access Info
        run: |
          Write-Host "`n========================================"
          Write-Host "🎯 RDP SERVER IS READY!"
          Write-Host "Username: Ady"
          Write-Host "Password: Akudankamu1@,"
          Write-Host "----------------------------------------"
          Write-Host "🌐 To find your RDP address, check logs above (LocalXpose Tunnel info)"
          Write-Host "Example: tcp://1.tcp.ap.localxpose.io:12345"
          Write-Host "========================================`n"

          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Press Stop Workflow to end session."
              Start-Sleep -Seconds 300
          }
